import 'package:almeyar/core/helpers/app_snack_bar.dart';
import 'package:almeyar/core/helpers/cache_helper.dart';
import 'package:almeyar/core/utils/exports.dart';
import 'package:almeyar/core/utils/loading_dialog.dart';
import 'package:almeyar/core/widgets/custom_icon_rounded_box.dart';
import 'package:almeyar/core/widgets/custom_rounder_arrow.dart';
import 'package:almeyar/core/widgets/details_info_row.dart';
import 'package:almeyar/core/widgets/details_info_section.dart';
import 'package:almeyar/core/widgets/password_text_form_field.dart';
import 'package:almeyar/core/widgets/status_badge.dart';
import 'package:almeyar/core/utils/async.dart';
import 'package:almeyar/core/network/api_error_model.dart';
import 'package:almeyar/core/network/local_status_codes.dart';
import 'package:almeyar/core/models/base_response.dart';
import 'package:almeyar/core/network/result.dart';
import 'dart:io';

// Core Services
import 'package:almeyar/core/services/internet_service.dart';
export 'package:almeyar/core/services/internet_service.dart';
import 'package:almeyar/core/services/image_picker_service.dart';
export 'package:almeyar/core/services/image_picker_service.dart';

// Models
import 'package:almeyar/features/profile/data/models/profile_model.dart';
export 'package:almeyar/features/profile/data/models/profile_model.dart';
import 'package:almeyar/features/profile/data/models/gift_card_model.dart';
export 'package:almeyar/features/profile/data/models/gift_card_model.dart';
import 'package:almeyar/core/models/message_model.dart';
export 'package:almeyar/core/models/message_model.dart';
import 'package:almeyar/core/models/message_response.dart';
export 'package:almeyar/core/models/message_response.dart';
import 'package:almeyar/features/profile/data/models/update_password_request.dart';
export 'package:almeyar/features/profile/data/models/update_password_request.dart';

// Repositories
import 'package:almeyar/features/profile/data/repos/profile_repo.dart';
export 'package:almeyar/features/profile/data/repos/profile_repo.dart';

// Widgets
import 'package:almeyar/core/widgets/phone_form_field.dart';
export 'package:almeyar/core/widgets/phone_form_field.dart';
import 'package:almeyar/core/widgets/internet_connection_widget.dart';
export 'package:almeyar/core/widgets/internet_connection_widget.dart';
import 'package:almeyar/core/widgets/custom_error_widget.dart';
export 'package:almeyar/core/widgets/custom_error_widget.dart';
import 'package:almeyar/core/widgets/custom_cached_image.dart';
export 'package:almeyar/core/widgets/custom_cached_image.dart';

// Cubits
import 'package:almeyar/features/profile/presentation/cubits/profile/profile_cubit.dart';

part 'views/profile_view.dart';
part 'views/edit_profile_view.dart';
part 'views/change_password_view.dart';
part 'views/app_info_view.dart';
part 'views/gift_cards_view.dart';
part 'cubits/gift_cards/gift_cards_cubit.dart';
part 'cubits/gift_cards/gift_cards_state.dart';
part 'cubits/update_profile/update_profile_cubit.dart';
part 'cubits/update_profile/update_profile_state.dart';
part 'cubits/change_password/change_password_cubit.dart';
part 'cubits/change_password/change_password_state.dart';
part 'cubits/app_info/app_info_cubit.dart';
part 'cubits/app_info/app_info_state.dart';
part 'widgets/profile/profile_view_body.dart';
part 'widgets/profile/profile_avatar_section.dart';
part 'widgets/profile/profile_menu_item.dart';
part 'widgets/profile/profile_error_widget.dart';
part 'widgets/profile/profile_logout_bloc_listener.dart';
part 'widgets/profile/logout_dialog_content.dart';

part 'widgets/edit_profile/edit_profile_view_body.dart';
part 'widgets/edit_profile/delete_account_dialog_content.dart';
part 'widgets/edit_profile/edit_profile_avatar_section.dart';
part 'widgets/edit_profile/edit_profile_info_card.dart';
part 'widgets/edit_profile/edit_profile_update_section.dart';
part 'widgets/edit_profile/edit_profile_save_button.dart';
part 'widgets/edit_profile/edit_profile_update_bloc_listener.dart';
part 'widgets/edit_profile/edit_profile_delete_account_bloc_listener.dart';
part 'widgets/change_password/change_password_view_body.dart';
part 'widgets/change_password/change_password_save_button.dart';
part 'widgets/change_password/change_password_bloc_listener.dart';
part 'widgets/app_info/app_info_view_body.dart';
part 'widgets/gift_cards/gift_cards_view_body.dart';
part 'widgets/gift_cards/gift_cards_list_view.dart';
part 'widgets/gift_cards/gift_card_item.dart';
part 'widgets/gift_cards/gift_card_header.dart';
part 'widgets/gift_cards/gift_card_info_rows.dart';
