class Routes {
  const Routes._();

  static const String onboarding = '/onboarding';
  static const String login = '/login';
  static const String register = '/register';
  static const String forgetPassword = '/forget-password';
  static const String otp = '/otp';
  static const String resetPassword = '/reset-password';
  static const String main = '/main';
  static const String shipmentAddresses = '/shipment-addresses';
  static const String shipmentAddressDetails = '/shipment-address-details';
  static const String requestReceiveShipmentView = '/request-receive-shipment';
  static const String receiveShipment = '/receive-shipment';
  static const String shipmentPickupRequests = '/shipment-pickup-requests';
  static const String shipmentPickupDetails = '/shipment-pickup-details';
  static const String priceCalculator = '/price-calculator';
  static const String shipmentsTracking = '/shipments-tracking';
  static const String shipmentsType = '/shipments-type';
  static const String shipmentDetails = '/shipment-details';
  static const String deliveryRequests = '/delivery-requests';
  static const String deliveryRequestsDetails = '/delivery-requests-details';
  static const String shoppingSites = '/shopping-sites';
  static const String purchaseOrders = '/purchase-orders';
  static const String addPurchaseOrder = '/add-purchase-order';
  static const String purchaseOrderDetails = '/purchase-order-details';
  static const String moneyTransfers = '/money-transfers';
  static const String addNewMoneyTransfer = '/add-new-money-transfer';
  static const String moneyTransferDetails = '/money-transfer-details';
  static const String profile = '/profile';
  static const String editProfile = '/edit-profile';
  static const String changePassword = '/change-password';
  static const String termsAndConditions = '/terms-and-conditions';
  static const String giftCards = '/gift-cards';
  static const String supportTickets = '/support-tickets';
  static const String addNewTicket = '/add-new-ticket';
  static const String ticketDetails = '/ticket-details';
  static const String wallets = '/wallets';
  static const String walletMoneyTransfer = '/wallet-money-transfer';
  static const String accountStatement = '/account-statement';
  static const String prohibited = '/prohibited';
}
